spring:
  application:
    name: businessassistant-login
  jmx:
    enabled: true

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
security:
  secret: SgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7 
  login: /v1/api/login        